### ISSUE TITLE
[Templates] Inverser les argumuments de render

### ISSUE THREAD

**Issue by SundayPlayer** [mtancoigne/FrameworkDevA3#19]
Il serai peut être plus simple d'inverser les arguments de la méthode render.

**Comment by NeodarZ** [comment]
@SundayPlayer, le problème est que du fait que le paramètre `$view` n'est pas obligatoire, si on le met en premier et que la fonction `render()` est utilisé de tel sorte que l'on lui passe uniquement un tableau de variables, PHP va attribuer à la variable `$view` le tableau de variables précédemment passer à la fonction `render()`...

N'y a t'il pas un moyen plus élégant de le faire ?

**Comment by mtancoigne** [comment]
`$view` devrait être obligatoire non ? dans le sens ou on le définit pour chaque action...

**Comment by SundayPlayer** [comment]
Je suis assez d'accord avec @mtancoigne dans le sens ou quand ou il n'y a pas de raisons d'avoir une vue par défaut ! Et au pire l'ordre peut etre quand même inversé et rendre les deux paramètres facultatifs ?!? => `render(string $template = 'delault.php', $param = [])`

**Comment by NeodarZ** [comment]
Oui c'est pas faux, alors va pour un paramètre obligatoire.
